### ISSUE TITLE
Missing config.ini parameters?

### ISSUE THREAD

**Issue by Alpoy** [kaschmo/sh_face_rec#10]
Hi,

I've been trying to make this work but I've been struggling with missing config parameters:
When running trainclassifier.py:
Section "TRAIN" with the parameter TRAINING_PATH (this was more or less easy to resolve)

And now I get an error message when running start.sh
added ./sh_face_rec/ to pythonpath.
Traceback (most recent call last):
  File "sh_face_rec/startserver.py", line 6, in <module>
    from frameworker import FrameWorker
  File "./sh_face_rec/frameworker.py", line 13, in <module>
    cf = config['FRAMEWORKER']
  File "/usr/lib/python3.4/configparser.py", line 937, in __getitem__
    raise KeyError(key)
KeyError: 'FRAMEWORKER'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***

**Comment by kaschmo** [comment]
Hi,

I have a config.ini that I use in production. Did not copy all the latest config categories over to the template. But now I did - see updated version of config_template.ini
Actually, the Frameworker section is not needed for configuration. So you could also completely delte the cf = config['FRAMEWORKER'] from frameworker.py

**Comment by Alpoy** [comment]
Seems to work fine now! Thanks :-)
